library(knitr)
library(rvest)
library(gsubfn)
library(tidyr)
library(tmap)
library(shiny)
library(readr)
library(dplyr)
library(readr)
library(tibble)
library(methods)
library(tidyverse)
library(ggplot2)
library(viridis)
library(sp)
library(rgdal)
library(rgeos)
library(raster)
library(tmap)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(cluster)
library(ggalt)
library(ranger)
library(janitor)
library(iml)

options(gsubfn.engine="R")

# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")
